parameters:
    env(MISEREND_GIT_VERSION): DEV

twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        git_version: "%env(resolve:MISEREND_GIT_VERSION)%"

when@test:
    twig:
        strict_variables: true
