FROM php:8.3-apache

WORKDIR /miserend

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

# Install php stuff
RUN apt-get update --fix-missing
 
RUN install-php-extensions mysqli pdo pdo_mysql gd intl imagick && a2enmod rewrite

# Settings
RUN service apache2 restart

# Fix Entrypoint Problmes
ENTRYPOINT ["./docker/entrypoint_miserend.sh"]
