export enum DialogResponse {
  SAVE_SIMPLE = 'SAVE_SIMPLE',
  MORE_DETAILS = 'MORE_DETAILS',

  SAVE = 'SAVE',

  DELETE_ALL = 'DELETE_ALL',
  DELETE_ONE = 'DELETE_ONE',

  EVENT_VIEWER_EDIT_ALL = 'EVENT_VIEWER_EDIT_ALL',
  EVENT_VIEWER_EDIT_ONE = 'EVENT_VIEWER_EDIT_ONE',

  CONTINUE = 'CONTINUE'

}
