name: "Static Analysis"

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - phpstan*
      - tests/StaticAnalysis/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/static-analysis.yml
      - composer.*
      - src/**
      - phpstan*
      - tests/StaticAnalysis/**

jobs:
  static-analysis-phpstan:
    name: Static Analysis with PHPStan
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: 8.3
          tools: cs2pr

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Symfony warmup
        run: |
          bin/console cache:warmup

      - name: Run static analysis with phpstan/phpstan
        run: "vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"
