name: Continuous Integration

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/symfony.yml
      - composer.*
      - phpunit.xml.dist
      - assets/**
      - config/**
      - src/**
      - templates/**
      - tests/**
      - translations/**
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/symfony.yml
      - composer.*
      - phpunit.xml.dist
      - assets/**
      - config/**
      - src/**
      - templates/**
      - tests/**
      - translations/**

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          node-version: 20

      - uses: actions/checkout@v3

      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm i

      - name: Build assets
        run: npm run build

      - name: Create Database
        run: |
          mkdir -p data
          touch data/database.sqlite

      - name: Unit tests
        run: vendor/bin/phpunit --testsuite unit --coverage-clover coverage-unit.xml

      - name: Application tests
        run: vendor/bin/phpunit --testsuite application --coverage-clover coverage-application.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./coverage-unit.xml,./coverage-application.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: borazslo/miserend.hu

